language: node_js
node_js:
  - "8.9.4"

before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
  - gem install bundler
  - bundle check || bundle install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master