# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Charlotte
email: info@opencharlotte.org
description: >- # this means to ignore newlines until "baseurl:"
  Open Charlotte
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.opencharlotte.org'
twitter_username: opencltbrigade
github_username: opencltbrigade

include: ['_pages', '_redirects']

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

pagination:
  permalink: '/page/:num/'
  sort_reverse: true
  sort_field: 'date'
  enabled: true
  per_page: 5
  limit: 0

navigation_top_left:
  - title: 'Events'
    url: /events/
  - title: 'Projects'
    url: /projects/
    new_window: true
  - title: 'About Us'
    url: /about/

navigation_top_right:
  - title: 'Civic Hack 2019'
    url: /civichack/
    new_window: true
  - title: 'Donate'
    url: /donate/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
