# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Charlotte
email: info@opencharlotte.org
description: >- # this means to ignore newlines until "baseurl:"
  Open Charlotte
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.opencharlotte.org'

social:
  facebook_url: https://facebook.com/opencltbrigade
  twitter_url: https://twitter.com/opencltbrigade
  medium_url: https://medium.com/opencltbrigade
  github_url: https://github.com/opencltbrigade

include: ['_pages', '_redirects']

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

pagination:
  permalink: '/page/:num/'
  sort_reverse: true
  sort_field: 'date'
  enabled: true
  per_page: 5
  limit: 0

navigation_top_left:
  - title: 'Brigade'
    url: /brigade/
  - title: 'Events'
    url: /events/
  - title: 'Projects'
    url: /projects/
    new_window: true
  - title: 'Code of Conduct'
    url: /code-of-conduct/
  - title: 'Blog'
    url: '/blog/'
    new_window: true
  - title: 'About Us'
    url: /about/

navigation_top_right:
  - title: 'Next Meetup'
    url: 'https://www.meetup.com/Open-Charlotte-Brigade/events/sqmrpqyzfbkc/'
    new_window: true

featured_event:
  headline: 'Join us at our next Project Night'
  date: 'March 27th, 2019 - 7:00pm to 9:00pm'
  description: 'You’re invited to help us re-image government and community services. Join our community of civic hackers, as we come together to help address problems that matter and make Charlotte more awesome.'
  href: 'https://www.meetup.com/Open-Charlotte-Brigade/events/sqmrpqyzfbkc/'
  background_image: '/img/event-bg.jpeg'

next_events:
  community_date: 'April 10, 2019'
  community_url: 'https://www.meetup.com/Open-Charlotte-Brigade/events/hvprpqyzgbnb/'
  project_date: 'March 27, 2019'
  project_url: 'https://www.meetup.com/Open-Charlotte-Brigade/events/sqmrpqyzfbkc/'
  social_date: 'Thursday, June 20 at Blue Blaze Brewing'
  social_url: 'https://www.meetup.com/Open-Charlotte-Brigade/events/257928950/'

leadership_team_members:
  - name: 'Jill Bjers'
    title: 'Director / Brigade Captain'
    photo: '/img/about/leadership/jill.jpg'
  - name: 'Andrew Natoli'
    title: 'Projects Lead'
    photo: '/img/about/leadership/andrew.jpg'
  - name: 'Kazi Smith'
    title: 'Marketing Lead'
    photo: '/img/about/leadership/kazi.jpg'
  - name: 'Jim Van Fleet'
    title: 'Senior Advisor'
    photo: '/img/about/leadership/jim.jpg'
  - name: 'Ryan Edge'
    title: 'Technology Lead'
  - name: 'Dawn Peterson'
    title: 'Communications Lead'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
